### ISSUE TITLE
README.adoc references non-existing "latest" docker tag

### ISSUE THREAD

**Issue by jzingler** [spring-io/artifactory-resource#32]
The `README.adoc` includes an example with `tag: latest` to pull down the latest docker image but there is no `latest` tag image in docker hub. I specified the `tag: 0.0.6` as a workaround.
```
resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: latest
```
