### ISSUE TITLE
Add support for HTTP proxy

### ISSUE THREAD

**Issue by gabipetrovay** [spring-io/artifactory-resource#69]
Opened this issue in case this is needed by your process for reviewing a PR: #68 

This PR adds the following extra two source properties: `proxy_host` and `proxy_port`

```yml
resources:
- name: artifacts
  type: artifactory-resource
  source:
    uri: https://repo.example.com
    username: admin
    password: secret
    build_name: my-build
    proxy_host: proxy.example.com
    proxy_port: 8080
```

See the PR or the [forked repo](https://github.com/gabipetrovay/artifactory-resource/tree/added-proxy-support#source-configuration) for the documentation.
