### ISSUE TITLE
Allow properties to be added into build-info.json

### ISSUE THREAD

**Issue by Ambarisha-006** [spring-io/artifactory-resource#70]
Currently "properties" field Instead of adding the properties to the `build-info.json`, it is setting properties for every file in the build. 

**What we wanted:** It will be great if it updates to `build-info.json`, and it can be fetched back by "save_build_info" flag

```yml
params:
  artifact_set:
  - include:
    - "/**/*.zip"
    exclude:
    - "/**/foo.zip"
    properties:
      zip-type: docs
      zip-deployed: false
```
