### ISSUE TITLE
Drop registry-image when Concourse is upgraded to 7.0.0 or later

### ISSUE THREAD

**Issue by philwebb** [spring-io/artifactory-resource#75]
We should remove the following lines when concourse is upgraded:

```
resource_types:
- name: registry-image
  type: registry-image
  source:
    repository: concourse/registry-image-resource
    tag: 1.1.0
```
